#include "Forest Green/monochrome.js";
#include "Forest Green/quad.js";
#include "Forest Green/analogic-complement.js";
#include "Forest Green/analogic.js";
#include "Forest Green/complement.js";
#include "Forest Green/monochrome-dark.js";
#include "Forest Green/triad.js";
#include "Forest Green/monochrome-light.js";
#include "Brown/monochrome.js";
#include "Brown/quad.js";
#include "Brown/analogic-complement.js";
#include "Brown/analogic.js";
#include "Brown/complement.js";
#include "Brown/monochrome-dark.js";
#include "Brown/triad.js";
#include "Brown/monochrome-light.js";
#include "Blush/monochrome.js";
#include "Blush/quad.js";
#include "Blush/analogic-complement.js";
#include "Blush/analogic.js";
#include "Blush/complement.js";
#include "Blush/monochrome-dark.js";
#include "Blush/triad.js";
#include "Blush/monochrome-light.js";
#include "Green/monochrome.js";
#include "Green/quad.js";
#include "Green/analogic-complement.js";
#include "Green/analogic.js";
#include "Green/complement.js";
#include "Green/monochrome-dark.js";
#include "Green/triad.js";
#include "Green/monochrome-light.js";
#include "Gray/monochrome.js";
#include "Gray/quad.js";
#include "Gray/analogic-complement.js";
#include "Gray/analogic.js";
#include "Gray/complement.js";
#include "Gray/monochrome-dark.js";
#include "Gray/triad.js";
#include "Gray/monochrome-light.js";
#include "Screamin Green/monochrome.js";
#include "Screamin Green/quad.js";
#include "Screamin Green/analogic-complement.js";
#include "Screamin Green/analogic.js";
#include "Screamin Green/complement.js";
#include "Screamin Green/monochrome-dark.js";
#include "Screamin Green/triad.js";
#include "Screamin Green/monochrome-light.js";
#include "Violet (Purple)/monochrome.js";
#include "Violet (Purple)/quad.js";
#include "Violet (Purple)/analogic-complement.js";
#include "Violet (Purple)/analogic.js";
#include "Violet (Purple)/complement.js";
#include "Violet (Purple)/monochrome-dark.js";
#include "Violet (Purple)/triad.js";
#include "Violet (Purple)/monochrome-light.js";
#include "Blue Gray/monochrome.js";
#include "Blue Gray/quad.js";
#include "Blue Gray/analogic-complement.js";
#include "Blue Gray/analogic.js";
#include "Blue Gray/complement.js";
#include "Blue Gray/monochrome-dark.js";
#include "Blue Gray/triad.js";
#include "Blue Gray/monochrome-light.js";
#include "Cornflower/monochrome.js";
#include "Cornflower/quad.js";
#include "Cornflower/analogic-complement.js";
#include "Cornflower/analogic.js";
#include "Cornflower/complement.js";
#include "Cornflower/monochrome-dark.js";
#include "Cornflower/triad.js";
#include "Cornflower/monochrome-light.js";
#include "Granny Smith Apple/monochrome.js";
#include "Granny Smith Apple/quad.js";
#include "Granny Smith Apple/analogic-complement.js";
#include "Granny Smith Apple/analogic.js";
#include "Granny Smith Apple/complement.js";
#include "Granny Smith Apple/monochrome-dark.js";
#include "Granny Smith Apple/triad.js";
#include "Granny Smith Apple/monochrome-light.js";
#include "Lavender/monochrome.js";
#include "Lavender/quad.js";
#include "Lavender/analogic-complement.js";
#include "Lavender/analogic.js";
#include "Lavender/complement.js";
#include "Lavender/monochrome-dark.js";
#include "Lavender/triad.js";
#include "Lavender/monochrome-light.js";
#include "Burnt Sienna/monochrome.js";
#include "Burnt Sienna/quad.js";
#include "Burnt Sienna/analogic-complement.js";
#include "Burnt Sienna/analogic.js";
#include "Burnt Sienna/complement.js";
#include "Burnt Sienna/monochrome-dark.js";
#include "Burnt Sienna/triad.js";
#include "Burnt Sienna/monochrome-light.js";
#include "Neon Carrot/monochrome.js";
#include "Neon Carrot/quad.js";
#include "Neon Carrot/analogic-complement.js";
#include "Neon Carrot/analogic.js";
#include "Neon Carrot/complement.js";
#include "Neon Carrot/monochrome-dark.js";
#include "Neon Carrot/triad.js";
#include "Neon Carrot/monochrome-light.js";
#include "Raw Umber/monochrome.js";
#include "Raw Umber/quad.js";
#include "Raw Umber/analogic-complement.js";
#include "Raw Umber/analogic.js";
#include "Raw Umber/complement.js";
#include "Raw Umber/monochrome-dark.js";
#include "Raw Umber/triad.js";
#include "Raw Umber/monochrome-light.js";
#include "Tumbleweed/monochrome.js";
#include "Tumbleweed/quad.js";
#include "Tumbleweed/analogic-complement.js";
#include "Tumbleweed/analogic.js";
#include "Tumbleweed/complement.js";
#include "Tumbleweed/monochrome-dark.js";
#include "Tumbleweed/triad.js";
#include "Tumbleweed/monochrome-light.js";
#include "Magenta/monochrome.js";
#include "Magenta/quad.js";
#include "Magenta/analogic-complement.js";
#include "Magenta/analogic.js";
#include "Magenta/complement.js";
#include "Magenta/monochrome-dark.js";
#include "Magenta/triad.js";
#include "Magenta/monochrome-light.js";
#include "Purple Pizzazz/monochrome.js";
#include "Purple Pizzazz/quad.js";
#include "Purple Pizzazz/analogic-complement.js";
#include "Purple Pizzazz/analogic.js";
#include "Purple Pizzazz/complement.js";
#include "Purple Pizzazz/monochrome-dark.js";
#include "Purple Pizzazz/triad.js";
#include "Purple Pizzazz/monochrome-light.js";
#include "Sunset Orange/monochrome.js";
#include "Sunset Orange/quad.js";
#include "Sunset Orange/analogic-complement.js";
#include "Sunset Orange/analogic.js";
#include "Sunset Orange/complement.js";
#include "Sunset Orange/monochrome-dark.js";
#include "Sunset Orange/triad.js";
#include "Sunset Orange/monochrome-light.js";
#include "Orange Red/monochrome.js";
#include "Orange Red/quad.js";
#include "Orange Red/analogic-complement.js";
#include "Orange Red/analogic.js";
#include "Orange Red/complement.js";
#include "Orange Red/monochrome-dark.js";
#include "Orange Red/triad.js";
#include "Orange Red/monochrome-light.js";
#include "Cadet Blue/monochrome.js";
#include "Cadet Blue/quad.js";
#include "Cadet Blue/analogic-complement.js";
#include "Cadet Blue/analogic.js";
#include "Cadet Blue/complement.js";
#include "Cadet Blue/monochrome-dark.js";
#include "Cadet Blue/triad.js";
#include "Cadet Blue/monochrome-light.js";
#include "Mahogany/monochrome.js";
#include "Mahogany/quad.js";
#include "Mahogany/analogic-complement.js";
#include "Mahogany/analogic.js";
#include "Mahogany/complement.js";
#include "Mahogany/monochrome-dark.js";
#include "Mahogany/triad.js";
#include "Mahogany/monochrome-light.js";
#include "Canary/monochrome.js";
#include "Canary/quad.js";
#include "Canary/analogic-complement.js";
#include "Canary/analogic.js";
#include "Canary/complement.js";
#include "Canary/monochrome-dark.js";
#include "Canary/triad.js";
#include "Canary/monochrome-light.js";
#include "Blue/monochrome.js";
#include "Blue/quad.js";
#include "Blue/analogic-complement.js";
#include "Blue/analogic.js";
#include "Blue/complement.js";
#include "Blue/monochrome-dark.js";
#include "Blue/triad.js";
#include "Blue/monochrome-light.js";
#include "Radical Red/monochrome.js";
#include "Radical Red/quad.js";
#include "Radical Red/analogic-complement.js";
#include "Radical Red/analogic.js";
#include "Radical Red/complement.js";
#include "Radical Red/monochrome-dark.js";
#include "Radical Red/triad.js";
#include "Radical Red/monochrome-light.js";
#include "Robins Egg Blue/monochrome.js";
#include "Robins Egg Blue/quad.js";
#include "Robins Egg Blue/analogic-complement.js";
#include "Robins Egg Blue/analogic.js";
#include "Robins Egg Blue/complement.js";
#include "Robins Egg Blue/monochrome-dark.js";
#include "Robins Egg Blue/triad.js";
#include "Robins Egg Blue/monochrome-light.js";
#include "Raw Sienna/monochrome.js";
#include "Raw Sienna/quad.js";
#include "Raw Sienna/analogic-complement.js";
#include "Raw Sienna/analogic.js";
#include "Raw Sienna/complement.js";
#include "Raw Sienna/monochrome-dark.js";
#include "Raw Sienna/triad.js";
#include "Raw Sienna/monochrome-light.js";
#include "Violet Red/monochrome.js";
#include "Violet Red/quad.js";
#include "Violet Red/analogic-complement.js";
#include "Violet Red/analogic.js";
#include "Violet Red/complement.js";
#include "Violet Red/monochrome-dark.js";
#include "Violet Red/triad.js";
#include "Violet Red/monochrome-light.js";
#include "Purple Mountains Majesty/monochrome.js";
#include "Purple Mountains Majesty/quad.js";
#include "Purple Mountains Majesty/analogic-complement.js";
#include "Purple Mountains Majesty/analogic.js";
#include "Purple Mountains Majesty/complement.js";
#include "Purple Mountains Majesty/monochrome-dark.js";
#include "Purple Mountains Majesty/triad.js";
#include "Purple Mountains Majesty/monochrome-light.js";
#include "Periwinkle/monochrome.js";
#include "Periwinkle/quad.js";
#include "Periwinkle/analogic-complement.js";
#include "Periwinkle/analogic.js";
#include "Periwinkle/complement.js";
#include "Periwinkle/monochrome-dark.js";
#include "Periwinkle/triad.js";
#include "Periwinkle/monochrome-light.js";
#include "Sunglow/monochrome.js";
#include "Sunglow/quad.js";
#include "Sunglow/analogic-complement.js";
#include "Sunglow/analogic.js";
#include "Sunglow/complement.js";
#include "Sunglow/monochrome-dark.js";
#include "Sunglow/triad.js";
#include "Sunglow/monochrome-light.js";
#include "Cotton Candy/monochrome.js";
#include "Cotton Candy/quad.js";
#include "Cotton Candy/analogic-complement.js";
#include "Cotton Candy/analogic.js";
#include "Cotton Candy/complement.js";
#include "Cotton Candy/monochrome-dark.js";
#include "Cotton Candy/triad.js";
#include "Cotton Candy/monochrome-light.js";
#include "Pine Green/monochrome.js";
#include "Pine Green/quad.js";
#include "Pine Green/analogic-complement.js";
#include "Pine Green/analogic.js";
#include "Pine Green/complement.js";
#include "Pine Green/monochrome-dark.js";
#include "Pine Green/triad.js";
#include "Pine Green/monochrome-light.js";
#include "Royal Purple/monochrome.js";
#include "Royal Purple/quad.js";
#include "Royal Purple/analogic-complement.js";
#include "Royal Purple/analogic.js";
#include "Royal Purple/complement.js";
#include "Royal Purple/monochrome-dark.js";
#include "Royal Purple/triad.js";
#include "Royal Purple/monochrome-light.js";
#include "Midnight Blue/monochrome.js";
#include "Midnight Blue/quad.js";
#include "Midnight Blue/analogic-complement.js";
#include "Midnight Blue/analogic.js";
#include "Midnight Blue/complement.js";
#include "Midnight Blue/monochrome-dark.js";
#include "Midnight Blue/triad.js";
#include "Midnight Blue/monochrome-light.js";
#include "Brick Red/monochrome.js";
#include "Brick Red/quad.js";
#include "Brick Red/analogic-complement.js";
#include "Brick Red/analogic.js";
#include "Brick Red/complement.js";
#include "Brick Red/monochrome-dark.js";
#include "Brick Red/triad.js";
#include "Brick Red/monochrome-light.js";
#include "Silver/monochrome.js";
#include "Silver/quad.js";
#include "Silver/analogic-complement.js";
#include "Silver/analogic.js";
#include "Silver/complement.js";
#include "Silver/monochrome-dark.js";
#include "Silver/triad.js";
#include "Silver/monochrome-light.js";
#include "Copper/monochrome.js";
#include "Copper/quad.js";
#include "Copper/analogic-complement.js";
#include "Copper/analogic.js";
#include "Copper/complement.js";
#include "Copper/monochrome-dark.js";
#include "Copper/triad.js";
#include "Copper/monochrome-light.js";
#include "Shadow/monochrome.js";
#include "Shadow/quad.js";
#include "Shadow/analogic-complement.js";
#include "Shadow/analogic.js";
#include "Shadow/complement.js";
#include "Shadow/monochrome-dark.js";
#include "Shadow/triad.js";
#include "Shadow/monochrome-light.js";
#include "Fuchsia/monochrome.js";
#include "Fuchsia/quad.js";
#include "Fuchsia/analogic-complement.js";
#include "Fuchsia/analogic.js";
#include "Fuchsia/complement.js";
#include "Fuchsia/monochrome-dark.js";
#include "Fuchsia/triad.js";
#include "Fuchsia/monochrome-light.js";
#include "Blue Green/monochrome.js";
#include "Blue Green/quad.js";
#include "Blue Green/analogic-complement.js";
#include "Blue Green/analogic.js";
#include "Blue Green/complement.js";
#include "Blue Green/monochrome-dark.js";
#include "Blue Green/triad.js";
#include "Blue Green/monochrome-light.js";
#include "Cerulean/monochrome.js";
#include "Cerulean/quad.js";
#include "Cerulean/analogic-complement.js";
#include "Cerulean/analogic.js";
#include "Cerulean/complement.js";
#include "Cerulean/monochrome-dark.js";
#include "Cerulean/triad.js";
#include "Cerulean/monochrome-light.js";
#include "Razzle Dazzle Rose/monochrome.js";
#include "Razzle Dazzle Rose/quad.js";
#include "Razzle Dazzle Rose/analogic-complement.js";
#include "Razzle Dazzle Rose/analogic.js";
#include "Razzle Dazzle Rose/complement.js";
#include "Razzle Dazzle Rose/monochrome-dark.js";
#include "Razzle Dazzle Rose/triad.js";
#include "Razzle Dazzle Rose/monochrome-light.js";
#include "Spring Green/monochrome.js";
#include "Spring Green/quad.js";
#include "Spring Green/analogic-complement.js";
#include "Spring Green/analogic.js";
#include "Spring Green/complement.js";
#include "Spring Green/monochrome-dark.js";
#include "Spring Green/triad.js";
#include "Spring Green/monochrome-light.js";
#include "Cerise/monochrome.js";
#include "Cerise/quad.js";
#include "Cerise/analogic-complement.js";
#include "Cerise/analogic.js";
#include "Cerise/complement.js";
#include "Cerise/monochrome-dark.js";
#include "Cerise/triad.js";
#include "Cerise/monochrome-light.js";
#include "Scarlet/monochrome.js";
#include "Scarlet/quad.js";
#include "Scarlet/analogic-complement.js";
#include "Scarlet/analogic.js";
#include "Scarlet/complement.js";
#include "Scarlet/monochrome-dark.js";
#include "Scarlet/triad.js";
#include "Scarlet/monochrome-light.js";
#include "Inchworm/monochrome.js";
#include "Inchworm/quad.js";
#include "Inchworm/analogic-complement.js";
#include "Inchworm/analogic.js";
#include "Inchworm/complement.js";
#include "Inchworm/monochrome-dark.js";
#include "Inchworm/triad.js";
#include "Inchworm/monochrome-light.js";
#include "Piggy Pink/monochrome.js";
#include "Piggy Pink/quad.js";
#include "Piggy Pink/analogic-complement.js";
#include "Piggy Pink/analogic.js";
#include "Piggy Pink/complement.js";
#include "Piggy Pink/monochrome-dark.js";
#include "Piggy Pink/triad.js";
#include "Piggy Pink/monochrome-light.js";
#include "Chestnut/monochrome.js";
#include "Chestnut/quad.js";
#include "Chestnut/analogic-complement.js";
#include "Chestnut/analogic.js";
#include "Chestnut/complement.js";
#include "Chestnut/monochrome-dark.js";
#include "Chestnut/triad.js";
#include "Chestnut/monochrome-light.js";
#include "Plum/monochrome.js";
#include "Plum/quad.js";
#include "Plum/analogic-complement.js";
#include "Plum/analogic.js";
#include "Plum/complement.js";
#include "Plum/monochrome-dark.js";
#include "Plum/triad.js";
#include "Plum/monochrome-light.js";
#include "Outer Space/monochrome.js";
#include "Outer Space/quad.js";
#include "Outer Space/analogic-complement.js";
#include "Outer Space/analogic.js";
#include "Outer Space/complement.js";
#include "Outer Space/monochrome-dark.js";
#include "Outer Space/triad.js";
#include "Outer Space/monochrome-light.js";
#include "Vivid Violet/monochrome.js";
#include "Vivid Violet/quad.js";
#include "Vivid Violet/analogic-complement.js";
#include "Vivid Violet/analogic.js";
#include "Vivid Violet/complement.js";
#include "Vivid Violet/monochrome-dark.js";
#include "Vivid Violet/triad.js";
#include "Vivid Violet/monochrome-light.js";
#include "Sea Green/monochrome.js";
#include "Sea Green/quad.js";
#include "Sea Green/analogic-complement.js";
#include "Sea Green/analogic.js";
#include "Sea Green/complement.js";
#include "Sea Green/monochrome-dark.js";
#include "Sea Green/triad.js";
#include "Sea Green/monochrome-light.js";
#include "Green Yellow/monochrome.js";
#include "Green Yellow/quad.js";
#include "Green Yellow/analogic-complement.js";
#include "Green Yellow/analogic.js";
#include "Green Yellow/complement.js";
#include "Green Yellow/monochrome-dark.js";
#include "Green Yellow/triad.js";
#include "Green Yellow/monochrome-light.js";
#include "Electric Lime/monochrome.js";
#include "Electric Lime/quad.js";
#include "Electric Lime/analogic-complement.js";
#include "Electric Lime/analogic.js";
#include "Electric Lime/complement.js";
#include "Electric Lime/monochrome-dark.js";
#include "Electric Lime/triad.js";
#include "Electric Lime/monochrome-light.js";
#include "Fuzzy Wuzzy Brown/monochrome.js";
#include "Fuzzy Wuzzy Brown/quad.js";
#include "Fuzzy Wuzzy Brown/analogic-complement.js";
#include "Fuzzy Wuzzy Brown/analogic.js";
#include "Fuzzy Wuzzy Brown/complement.js";
#include "Fuzzy Wuzzy Brown/monochrome-dark.js";
#include "Fuzzy Wuzzy Brown/triad.js";
#include "Fuzzy Wuzzy Brown/monochrome-light.js";
#include "Indigo/monochrome.js";
#include "Indigo/quad.js";
#include "Indigo/analogic-complement.js";
#include "Indigo/analogic.js";
#include "Indigo/complement.js";
#include "Indigo/monochrome-dark.js";
#include "Indigo/triad.js";
#include "Indigo/monochrome-light.js";
#include "Sepia/monochrome.js";
#include "Sepia/quad.js";
#include "Sepia/analogic-complement.js";
#include "Sepia/analogic.js";
#include "Sepia/complement.js";
#include "Sepia/monochrome-dark.js";
#include "Sepia/triad.js";
#include "Sepia/monochrome-light.js";
#include "Goldenrod/monochrome.js";
#include "Goldenrod/quad.js";
#include "Goldenrod/analogic-complement.js";
#include "Goldenrod/analogic.js";
#include "Goldenrod/complement.js";
#include "Goldenrod/monochrome-dark.js";
#include "Goldenrod/triad.js";
#include "Goldenrod/monochrome-light.js";
#include "Red/monochrome.js";
#include "Red/quad.js";
#include "Red/analogic-complement.js";
#include "Red/analogic.js";
#include "Red/complement.js";
#include "Red/monochrome-dark.js";
#include "Red/triad.js";
#include "Red/monochrome-light.js";
#include "Beaver/monochrome.js";
#include "Beaver/quad.js";
#include "Beaver/analogic-complement.js";
#include "Beaver/analogic.js";
#include "Beaver/complement.js";
#include "Beaver/monochrome-dark.js";
#include "Beaver/triad.js";
#include "Beaver/monochrome-light.js";
#include "Shocking Pink/monochrome.js";
#include "Shocking Pink/quad.js";
#include "Shocking Pink/analogic-complement.js";
#include "Shocking Pink/analogic.js";
#include "Shocking Pink/complement.js";
#include "Shocking Pink/monochrome-dark.js";
#include "Shocking Pink/triad.js";
#include "Shocking Pink/monochrome-light.js";
#include "Gold/monochrome.js";
#include "Gold/quad.js";
#include "Gold/analogic-complement.js";
#include "Gold/analogic.js";
#include "Gold/complement.js";
#include "Gold/monochrome-dark.js";
#include "Gold/triad.js";
#include "Gold/monochrome-light.js";
#include "Orange Yellow/monochrome.js";
#include "Orange Yellow/quad.js";
#include "Orange Yellow/analogic-complement.js";
#include "Orange Yellow/analogic.js";
#include "Orange Yellow/complement.js";
#include "Orange Yellow/monochrome-dark.js";
#include "Orange Yellow/triad.js";
#include "Orange Yellow/monochrome-light.js";
#include "Antique Brass/monochrome.js";
#include "Antique Brass/quad.js";
#include "Antique Brass/analogic-complement.js";
#include "Antique Brass/analogic.js";
#include "Antique Brass/complement.js";
#include "Antique Brass/monochrome-dark.js";
#include "Antique Brass/triad.js";
#include "Antique Brass/monochrome-light.js";
#include "Fern/monochrome.js";
#include "Fern/quad.js";
#include "Fern/analogic-complement.js";
#include "Fern/analogic.js";
#include "Fern/complement.js";
#include "Fern/monochrome-dark.js";
#include "Fern/triad.js";
#include "Fern/monochrome-light.js";
#include "Sky Blue/monochrome.js";
#include "Sky Blue/quad.js";
#include "Sky Blue/analogic-complement.js";
#include "Sky Blue/analogic.js";
#include "Sky Blue/complement.js";
#include "Sky Blue/monochrome-dark.js";
#include "Sky Blue/triad.js";
#include "Sky Blue/monochrome-light.js";
#include "Shamrock/monochrome.js";
#include "Shamrock/quad.js";
#include "Shamrock/analogic-complement.js";
#include "Shamrock/analogic.js";
#include "Shamrock/complement.js";
#include "Shamrock/monochrome-dark.js";
#include "Shamrock/triad.js";
#include "Shamrock/monochrome-light.js";
#include "Caribbean Green/monochrome.js";
#include "Caribbean Green/quad.js";
#include "Caribbean Green/analogic-complement.js";
#include "Caribbean Green/analogic.js";
#include "Caribbean Green/complement.js";
#include "Caribbean Green/monochrome-dark.js";
#include "Caribbean Green/triad.js";
#include "Caribbean Green/monochrome-light.js";
#include "Purple Heart/monochrome.js";
#include "Purple Heart/quad.js";
#include "Purple Heart/analogic-complement.js";
#include "Purple Heart/analogic.js";
#include "Purple Heart/complement.js";
#include "Purple Heart/monochrome-dark.js";
#include "Purple Heart/triad.js";
#include "Purple Heart/monochrome-light.js";
#include "Violet Blue/monochrome.js";
#include "Violet Blue/quad.js";
#include "Violet Blue/analogic-complement.js";
#include "Violet Blue/analogic.js";
#include "Violet Blue/complement.js";
#include "Violet Blue/monochrome-dark.js";
#include "Violet Blue/triad.js";
#include "Violet Blue/monochrome-light.js";
#include "Razzmatazz/monochrome.js";
#include "Razzmatazz/quad.js";
#include "Razzmatazz/analogic-complement.js";
#include "Razzmatazz/analogic.js";
#include "Razzmatazz/complement.js";
#include "Razzmatazz/monochrome-dark.js";
#include "Razzmatazz/triad.js";
#include "Razzmatazz/monochrome-light.js";
#include "Denim/monochrome.js";
#include "Denim/quad.js";
#include "Denim/analogic-complement.js";
#include "Denim/analogic.js";
#include "Denim/complement.js";
#include "Denim/monochrome-dark.js";
#include "Denim/triad.js";
#include "Denim/monochrome-light.js";
#include "Almond/monochrome.js";
#include "Almond/quad.js";
#include "Almond/analogic-complement.js";
#include "Almond/analogic.js";
#include "Almond/complement.js";
#include "Almond/monochrome-dark.js";
#include "Almond/triad.js";
#include "Almond/monochrome-light.js";
#include "Red Violet/monochrome.js";
#include "Red Violet/quad.js";
#include "Red Violet/analogic-complement.js";
#include "Red Violet/analogic.js";
#include "Red Violet/complement.js";
#include "Red Violet/monochrome-dark.js";
#include "Red Violet/triad.js";
#include "Red Violet/monochrome-light.js";
#include "Outrageous Orange/monochrome.js";
#include "Outrageous Orange/quad.js";
#include "Outrageous Orange/analogic-complement.js";
#include "Outrageous Orange/analogic.js";
#include "Outrageous Orange/complement.js";
#include "Outrageous Orange/monochrome-dark.js";
#include "Outrageous Orange/triad.js";
#include "Outrageous Orange/monochrome-light.js";
#include "Bittersweet/monochrome.js";
#include "Bittersweet/quad.js";
#include "Bittersweet/analogic-complement.js";
#include "Bittersweet/analogic.js";
#include "Bittersweet/complement.js";
#include "Bittersweet/monochrome-dark.js";
#include "Bittersweet/triad.js";
#include "Bittersweet/monochrome-light.js";
#include "Apricot/monochrome.js";
#include "Apricot/quad.js";
#include "Apricot/analogic-complement.js";
#include "Apricot/analogic.js";
#include "Apricot/complement.js";
#include "Apricot/monochrome-dark.js";
#include "Apricot/triad.js";
#include "Apricot/monochrome-light.js";
#include "Eggplant/monochrome.js";
#include "Eggplant/quad.js";
#include "Eggplant/analogic-complement.js";
#include "Eggplant/analogic.js";
#include "Eggplant/complement.js";
#include "Eggplant/monochrome-dark.js";
#include "Eggplant/triad.js";
#include "Eggplant/monochrome-light.js";
#include "Navy Blue/monochrome.js";
#include "Navy Blue/quad.js";
#include "Navy Blue/analogic-complement.js";
#include "Navy Blue/analogic.js";
#include "Navy Blue/complement.js";
#include "Navy Blue/monochrome-dark.js";
#include "Navy Blue/triad.js";
#include "Navy Blue/monochrome-light.js";
#include "Vivid Tangerine/monochrome.js";
#include "Vivid Tangerine/quad.js";
#include "Vivid Tangerine/analogic-complement.js";
#include "Vivid Tangerine/analogic.js";
#include "Vivid Tangerine/complement.js";
#include "Vivid Tangerine/monochrome-dark.js";
#include "Vivid Tangerine/triad.js";
#include "Vivid Tangerine/monochrome-light.js";
#include "Blue Bell/monochrome.js";
#include "Blue Bell/quad.js";
#include "Blue Bell/analogic-complement.js";
#include "Blue Bell/analogic.js";
#include "Blue Bell/complement.js";
#include "Blue Bell/monochrome-dark.js";
#include "Blue Bell/triad.js";
#include "Blue Bell/monochrome-light.js";
#include "Jazzberry Jam/monochrome.js";
#include "Jazzberry Jam/quad.js";
#include "Jazzberry Jam/analogic-complement.js";
#include "Jazzberry Jam/analogic.js";
#include "Jazzberry Jam/complement.js";
#include "Jazzberry Jam/monochrome-dark.js";
#include "Jazzberry Jam/triad.js";
#include "Jazzberry Jam/monochrome-light.js";
#include "Asparagus/monochrome.js";
#include "Asparagus/quad.js";
#include "Asparagus/analogic-complement.js";
#include "Asparagus/analogic.js";
#include "Asparagus/complement.js";
#include "Asparagus/monochrome-dark.js";
#include "Asparagus/triad.js";
#include "Asparagus/monochrome-light.js";
#include "Pacific Blue/monochrome.js";
#include "Pacific Blue/quad.js";
#include "Pacific Blue/analogic-complement.js";
#include "Pacific Blue/analogic.js";
#include "Pacific Blue/complement.js";
#include "Pacific Blue/monochrome-dark.js";
#include "Pacific Blue/triad.js";
#include "Pacific Blue/monochrome-light.js";
#include "Dandelion/monochrome.js";
#include "Dandelion/quad.js";
#include "Dandelion/analogic-complement.js";
#include "Dandelion/analogic.js";
#include "Dandelion/complement.js";
#include "Dandelion/monochrome-dark.js";
#include "Dandelion/triad.js";
#include "Dandelion/monochrome-light.js";
#include "Blue Violet/monochrome.js";
#include "Blue Violet/quad.js";
#include "Blue Violet/analogic-complement.js";
#include "Blue Violet/analogic.js";
#include "Blue Violet/complement.js";
#include "Blue Violet/monochrome-dark.js";
#include "Blue Violet/triad.js";
#include "Blue Violet/monochrome-light.js";
#include "Carnation Pink/monochrome.js";
#include "Carnation Pink/quad.js";
#include "Carnation Pink/analogic-complement.js";
#include "Carnation Pink/analogic.js";
#include "Carnation Pink/complement.js";
#include "Carnation Pink/monochrome-dark.js";
#include "Carnation Pink/triad.js";
#include "Carnation Pink/monochrome-light.js";
#include "Atomic Tangerine/monochrome.js";
#include "Atomic Tangerine/quad.js";
#include "Atomic Tangerine/analogic-complement.js";
#include "Atomic Tangerine/analogic.js";
#include "Atomic Tangerine/complement.js";
#include "Atomic Tangerine/monochrome-dark.js";
#include "Atomic Tangerine/triad.js";
#include "Atomic Tangerine/monochrome-light.js";
#include "Maroon/monochrome.js";
#include "Maroon/quad.js";
#include "Maroon/analogic-complement.js";
#include "Maroon/analogic.js";
#include "Maroon/complement.js";
#include "Maroon/monochrome-dark.js";
#include "Maroon/triad.js";
#include "Maroon/monochrome-light.js";
#include "Burnt Orange/monochrome.js";
#include "Burnt Orange/quad.js";
#include "Burnt Orange/analogic-complement.js";
#include "Burnt Orange/analogic.js";
#include "Burnt Orange/complement.js";
#include "Burnt Orange/monochrome-dark.js";
#include "Burnt Orange/triad.js";
#include "Burnt Orange/monochrome-light.js";
#include "Tropical Rain Forest/monochrome.js";
#include "Tropical Rain Forest/quad.js";
#include "Tropical Rain Forest/analogic-complement.js";
#include "Tropical Rain Forest/analogic.js";
#include "Tropical Rain Forest/complement.js";
#include "Tropical Rain Forest/monochrome-dark.js";
#include "Tropical Rain Forest/triad.js";
#include "Tropical Rain Forest/monochrome-light.js";
#include "Mango Tango/monochrome.js";
#include "Mango Tango/quad.js";
#include "Mango Tango/analogic-complement.js";
#include "Mango Tango/analogic.js";
#include "Mango Tango/complement.js";
#include "Mango Tango/monochrome-dark.js";
#include "Mango Tango/triad.js";
#include "Mango Tango/monochrome-light.js";
#include "Pink Flamingo/monochrome.js";
#include "Pink Flamingo/quad.js";
#include "Pink Flamingo/analogic-complement.js";
#include "Pink Flamingo/analogic.js";
#include "Pink Flamingo/complement.js";
#include "Pink Flamingo/monochrome-dark.js";
#include "Pink Flamingo/triad.js";
#include "Pink Flamingo/monochrome-light.js";
#include "Orchid/monochrome.js";
#include "Orchid/quad.js";
#include "Orchid/analogic-complement.js";
#include "Orchid/analogic.js";
#include "Orchid/complement.js";
#include "Orchid/monochrome-dark.js";
#include "Orchid/triad.js";
#include "Orchid/monochrome-light.js";
#include "Jungle Green/monochrome.js";
#include "Jungle Green/quad.js";
#include "Jungle Green/analogic-complement.js";
#include "Jungle Green/analogic.js";
#include "Jungle Green/complement.js";
#include "Jungle Green/monochrome-dark.js";
#include "Jungle Green/triad.js";
#include "Jungle Green/monochrome-light.js";
#include "White/monochrome.js";
#include "White/quad.js";
#include "White/analogic-complement.js";
#include "White/analogic.js";
#include "White/complement.js";
#include "White/monochrome-dark.js";
#include "White/triad.js";
#include "White/monochrome-light.js";
#include "Hot Magenta/monochrome.js";
#include "Hot Magenta/quad.js";
#include "Hot Magenta/analogic-complement.js";
#include "Hot Magenta/analogic.js";
#include "Hot Magenta/complement.js";
#include "Hot Magenta/monochrome-dark.js";
#include "Hot Magenta/triad.js";
#include "Hot Magenta/monochrome-light.js";
#include "Aquamarine/monochrome.js";
#include "Aquamarine/quad.js";
#include "Aquamarine/analogic-complement.js";
#include "Aquamarine/analogic.js";
#include "Aquamarine/complement.js";
#include "Aquamarine/monochrome-dark.js";
#include "Aquamarine/triad.js";
#include "Aquamarine/monochrome-light.js";
#include "Black/monochrome.js";
#include "Black/quad.js";
#include "Black/analogic-complement.js";
#include "Black/analogic.js";
#include "Black/complement.js";
#include "Black/monochrome-dark.js";
#include "Black/triad.js";
#include "Black/monochrome-light.js";
#include "Macaroni and Cheese/monochrome.js";
#include "Macaroni and Cheese/quad.js";
#include "Macaroni and Cheese/analogic-complement.js";
#include "Macaroni and Cheese/analogic.js";
#include "Macaroni and Cheese/complement.js";
#include "Macaroni and Cheese/monochrome-dark.js";
#include "Macaroni and Cheese/triad.js";
#include "Macaroni and Cheese/monochrome-light.js";
#include "Unmellow Yellow/monochrome.js";
#include "Unmellow Yellow/quad.js";
#include "Unmellow Yellow/analogic-complement.js";
#include "Unmellow Yellow/analogic.js";
#include "Unmellow Yellow/complement.js";
#include "Unmellow Yellow/monochrome-dark.js";
#include "Unmellow Yellow/triad.js";
#include "Unmellow Yellow/monochrome-light.js";
#include "Mauvelous/monochrome.js";
#include "Mauvelous/quad.js";
#include "Mauvelous/analogic-complement.js";
#include "Mauvelous/analogic.js";
#include "Mauvelous/complement.js";
#include "Mauvelous/monochrome-dark.js";
#include "Mauvelous/triad.js";
#include "Mauvelous/monochrome-light.js";
#include "illustrator-scripting-guide/searchindex.js";
#include "illustrator-scripting-guide/_static/underscore.js";
#include "illustrator-scripting-guide/_static/documentation_options.js";
#include "illustrator-scripting-guide/_static/searchtools.js";
#include "illustrator-scripting-guide/_static/_sphinx_javascript_frameworks_compat.js";
#include "illustrator-scripting-guide/_static/language_data.js";
#include "illustrator-scripting-guide/_static/jquery-3.6.0.js";
#include "illustrator-scripting-guide/_static/doctools.js";
#include "illustrator-scripting-guide/_static/jquery.js";
#include "illustrator-scripting-guide/_static/underscore-1.13.1.js";
#include "illustrator-scripting-guide/_static/js/badge_only.js";
#include "illustrator-scripting-guide/_static/js/theme.js";
#include "illustrator-scripting-guide/_static/js/html5shiv.min.js";
#include "illustrator-scripting-guide/_static/js/html5shiv-printshiv.min.js";
#include "illustrator-scripting-guide/_static/dark_mode_js/theme_switcher.js";
#include "illustrator-scripting-guide/_static/dark_mode_js/default_light.js";
#include "illustrator-scripting-guide/_static/dark_mode_js/default_dark.js";
#include "illustrator-scripting-guide/build/json/_static/underscore.js";
#include "illustrator-scripting-guide/build/json/_static/documentation_options.js";
#include "illustrator-scripting-guide/build/json/_static/searchtools.js";
#include "illustrator-scripting-guide/build/json/_static/_sphinx_javascript_frameworks_compat.js";
#include "illustrator-scripting-guide/build/json/_static/language_data.js";
#include "illustrator-scripting-guide/build/json/_static/jquery-3.6.0.js";
#include "illustrator-scripting-guide/build/json/_static/doctools.js";
#include "illustrator-scripting-guide/build/json/_static/jquery.js";
#include "illustrator-scripting-guide/build/json/_static/underscore-1.13.1.js";
#include "illustrator-scripting-guide/build/json/_static/js/badge_only.js";
#include "illustrator-scripting-guide/build/json/_static/js/theme.js";
#include "illustrator-scripting-guide/build/json/_static/js/html5shiv.min.js";
#include "illustrator-scripting-guide/build/json/_static/js/html5shiv-printshiv.min.js";
#include "illustrator-scripting-guide/build/json/_static/dark_mode_js/theme_switcher.js";
#include "illustrator-scripting-guide/build/json/_static/dark_mode_js/default_light.js";
#include "illustrator-scripting-guide/build/json/_static/dark_mode_js/default_dark.js";
#include "Laser Lemon/monochrome.js";
#include "Laser Lemon/quad.js";
#include "Laser Lemon/analogic-complement.js";
#include "Laser Lemon/analogic.js";
#include "Laser Lemon/complement.js";
#include "Laser Lemon/monochrome-dark.js";
#include "Laser Lemon/triad.js";
#include "Laser Lemon/monochrome-light.js";
#include "Olive Green/monochrome.js";
#include "Olive Green/quad.js";
#include "Olive Green/analogic-complement.js";
#include "Olive Green/analogic.js";
#include "Olive Green/complement.js";
#include "Olive Green/monochrome-dark.js";
#include "Olive Green/triad.js";
#include "Olive Green/monochrome-light.js";
#include "Tan/monochrome.js";
#include "Tan/quad.js";
#include "Tan/analogic-complement.js";
#include "Tan/analogic.js";
#include "Tan/complement.js";
#include "Tan/monochrome-dark.js";
#include "Tan/triad.js";
#include "Tan/monochrome-light.js";
#include "Banana Mania/monochrome.js";
#include "Banana Mania/quad.js";
#include "Banana Mania/analogic-complement.js";
#include "Banana Mania/analogic.js";
#include "Banana Mania/complement.js";
#include "Banana Mania/monochrome-dark.js";
#include "Banana Mania/triad.js";
#include "Banana Mania/monochrome-light.js";
#include "Red Orange/monochrome.js";
#include "Red Orange/quad.js";
#include "Red Orange/analogic-complement.js";
#include "Red Orange/analogic.js";
#include "Red Orange/complement.js";
#include "Red Orange/monochrome-dark.js";
#include "Red Orange/triad.js";
#include "Red Orange/monochrome-light.js";
#include "Turquoise Blue/monochrome.js";
#include "Turquoise Blue/quad.js";
#include "Turquoise Blue/analogic-complement.js";
#include "Turquoise Blue/analogic.js";
#include "Turquoise Blue/complement.js";
#include "Turquoise Blue/monochrome-dark.js";
#include "Turquoise Blue/triad.js";
#include "Turquoise Blue/monochrome-light.js";
#include "Melon/monochrome.js";
#include "Melon/quad.js";
#include "Melon/analogic-complement.js";
#include "Melon/analogic.js";
#include "Melon/complement.js";
#include "Melon/monochrome-dark.js";
#include "Melon/triad.js";
#include "Melon/monochrome-light.js";
#include "Manatee/monochrome.js";
#include "Manatee/quad.js";
#include "Manatee/analogic-complement.js";
#include "Manatee/analogic.js";
#include "Manatee/complement.js";
#include "Manatee/monochrome-dark.js";
#include "Manatee/triad.js";
#include "Manatee/monochrome-light.js";
#include "Orange/monochrome.js";
#include "Orange/quad.js";
#include "Orange/analogic-complement.js";
#include "Orange/analogic.js";
#include "Orange/complement.js";
#include "Orange/monochrome-dark.js";
#include "Orange/triad.js";
#include "Orange/monochrome-light.js";
#include "Pink Sherbet/monochrome.js";
#include "Pink Sherbet/quad.js";
#include "Pink Sherbet/analogic-complement.js";
#include "Pink Sherbet/analogic.js";
#include "Pink Sherbet/complement.js";
#include "Pink Sherbet/monochrome-dark.js";
#include "Pink Sherbet/triad.js";
#include "Pink Sherbet/monochrome-light.js";
#include "Mountain Meadow/monochrome.js";
#include "Mountain Meadow/quad.js";
#include "Mountain Meadow/analogic-complement.js";
#include "Mountain Meadow/analogic.js";
#include "Mountain Meadow/complement.js";
#include "Mountain Meadow/monochrome-dark.js";
#include "Mountain Meadow/triad.js";
#include "Mountain Meadow/monochrome-light.js";
#include "Salmon/monochrome.js";
#include "Salmon/quad.js";
#include "Salmon/analogic-complement.js";
#include "Salmon/analogic.js";
#include "Salmon/complement.js";
#include "Salmon/monochrome-dark.js";
#include "Salmon/triad.js";
#include "Salmon/monochrome-light.js";
#include "Peach/monochrome.js";
#include "Peach/quad.js";
#include "Peach/analogic-complement.js";
#include "Peach/analogic.js";
#include "Peach/complement.js";
#include "Peach/monochrome-dark.js";
#include "Peach/triad.js";
#include "Peach/monochrome-light.js";
